name=input("Enter name=")
branch=input("Enter Branch=")
gender=input("Enter Gender=")
age=int(input("Enter Age="))
college=input("Enter college Name=")
print("Name is",name)
print("Branch is",branch)
print("Gender is",gender)
print("Age is",age)
print("college Name is",college)
